= Codename One Kotlin Runtime Library

This library provides support for https://kotlinlang.org/[Kotlin] in https://www.codenameone.com[Codename One].

== Requirements

. Currently development/compilation must be performed in IntelliJ IDEA
. The latest Codename One plugin installed (Actually, at time of writing the plugin with support for this hasn't been released yet.. will be released July 7, 2017).

== Supported Runtime Platforms

This should work in all platforms.

== Installation

Copy the the kotlin-runtime.cn1lib into your project's lib directory, and select "Codename One" -> "Refresh CN1Libs".

or

Install using the Extensions section of Codename One settings.

== Usage

As long as your project includes this runtime library, you should be able to add Kotlin classes and files directly inside your Codename One project when using IntelliJ IDE.
If you don't include this library and your project includes Kotlin code, then your app will still work in the simulator.  It will fail when you try to build for device though.  Adding this
library to your project will resolve such build errors.

== Building from Source

1. Replace the jars of the kotlin-jars directory with the jars for the version of the kotlin stdlib that you want to include in the cn1lib.
2. Run `ant`

== Tests

See the https://github.com/shannah/CN1KotlinTests[CN1KotlinTests project] for unit tests, which are being adapted from the tests in the official Kotlin repository.

== Links

. https://kotlinlang.org/[Kotlin Homepage]
. https://www.codenameone.com/[Codename One Homepage]
